### ISSUE TITLE
如何设置单机并行

### ISSUE THREAD

**Issue by wind-hx** [xuxueli/xxl-job#2529]
同一个任务3秒执行一次，一次需要1分钟，如何让任务并行

**Comment by xiaoxin19950218** [comment]
可以使用线程池

**Comment by yuxiao97** [comment]
感觉这个需求有点奇怪，3秒执行一次，执行却要1分钟，不会冲突？导致数据不一致嘛？
楼上说的线程池，用不了多久就用光了，没法玩。

**Comment by xiaoxin19950218** [comment]
20个就够了，三秒执行一次。一次一分钟。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月30日(周五) 中午1:55
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xuxueli/xxl-job] 如何设置单机并行 (#2529)




 
感觉这个需求有点奇怪，3秒执行一次，执行却要1分钟，不会冲突？导致数据不一致嘛？
 楼上说的线程池，用不了多久就用光了，没法玩。

**Comment by yuxiao97** [comment]
> 20个就够了，三秒执行一次。一次一分钟。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年7月30日(周五) 中午1:55 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [xuxueli/xxl-job] 如何设置单机并行 (#2529) 感觉这个需求有点奇怪，3秒执行一次，执行却要1分钟，不会冲突？导致数据不一致嘛？ 楼上说的线程池，用不了多久就用光了，没法玩。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

执行过程是占用线程的，在任务执行完之前线程是被一直占用的，后续的定时任务如何持续分配线程？

**Comment by xiaoxin19950218** [comment]
你在接口层设置一个线程池。就可以进来了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月30日(周五) 下午2:13
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xuxueli/xxl-job] 如何设置单机并行 (#2529)




  
20个就够了，三秒执行一次。一次一分钟。
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2021年7月30日(周五) 中午1:55 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [xuxueli/xxl-job] 如何设置单机并行 (#2529) 感觉这个需求有点奇怪，3秒执行一次，执行却要1分钟，不会冲突？导致数据不一致嘛？ 楼上说的线程池，用不了多久就用光了，没法玩。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
执行过程是占用线程的，在任务执行完之前线程是被一直占用的，后续的定时任务如何持续分配线程？

**Comment by yuxiao97** [comment]
> 你在接口层设置一个线程池。就可以进来了
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年7月30日(周五) 下午2:13 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [xuxueli/xxl-job] 如何设置单机并行 (#2529) 20个就够了，三秒执行一次。一次一分钟。 … ---原始邮件--- 发件人: @.&gt; 发送时间: 2021年7月30日(周五) 中午1:55 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [xuxueli/xxl-job] 如何设置单机并行 (#2529) 感觉这个需求有点奇怪，3秒执行一次，执行却要1分钟，不会冲突？导致数据不一致嘛？ 楼上说的线程池，用不了多久就用光了，没法玩。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 执行过程是占用线程的，在任务执行完之前线程是被一直占用的，后续的定时任务如何持续分配线程？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

嗯，一下没反应过来哈

**Comment by xiaoxin19950218** [comment]
数据不一致可以通过业务代码控制



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月30日(周五) 下午2:19
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xuxueli/xxl-job] 如何设置单机并行 (#2529)




  
你在接口层设置一个线程池。就可以进来了
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2021年7月30日(周五) 下午2:13 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [xuxueli/xxl-job] 如何设置单机并行 (#2529) 20个就够了，三秒执行一次。一次一分钟。 … ---原始邮件--- 发件人: @.&gt; 发送时间: 2021年7月30日(周五) 中午1:55 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [xuxueli/xxl-job] 如何设置单机并行 (#2529) 感觉这个需求有点奇怪，3秒执行一次，执行却要1分钟，不会冲突？导致数据不一致嘛？ 楼上说的线程池，用不了多久就用光了，没法玩。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 执行过程是占用线程的，在任务执行完之前线程是被一直占用的，后续的定时任务如何持续分配线程？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
嗯，一下没反应过来哈

**Comment by yuxiao97** [comment]
> 数据不一致可以通过业务代码控制
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年7月30日(周五) 下午2:19 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [xuxueli/xxl-job] 如何设置单机并行 (#2529) 你在接口层设置一个线程池。就可以进来了 … ---原始邮件--- 发件人: @.&gt; 发送时间: 2021年7月30日(周五) 下午2:13 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [xuxueli/xxl-job] 如何设置单机并行 (#2529) 20个就够了，三秒执行一次。一次一分钟。 … ---原始邮件--- 发件人: @.&gt; 发送时间: 2021年7月30日(周五) 中午1:55 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [xuxueli/xxl-job] 如何设置单机并行 (#2529) 感觉这个需求有点奇怪，3秒执行一次，执行却要1分钟，不会冲突？导致数据不一致嘛？ 楼上说的线程池，用不了多久就用光了，没法玩。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 执行过程是占用线程的，在任务执行完之前线程是被一直占用的，后续的定时任务如何持续分配线程？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 嗯，一下没反应过来哈 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

原始感觉就是这个任务调度周期就不太合理。

**Comment by xiaoxin19950218** [comment]
你修改成一分钟执行一次不就行了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月30日(周五) 下午2:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xuxueli/xxl-job] 如何设置单机并行 (#2529)




  
数据不一致可以通过业务代码控制
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2021年7月30日(周五) 下午2:19 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [xuxueli/xxl-job] 如何设置单机并行 (#2529) 你在接口层设置一个线程池。就可以进来了 … ---原始邮件--- 发件人: @.&gt; 发送时间: 2021年7月30日(周五) 下午2:13 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [xuxueli/xxl-job] 如何设置单机并行 (#2529) 20个就够了，三秒执行一次。一次一分钟。 … ---原始邮件--- 发件人: @.&gt; 发送时间: 2021年7月30日(周五) 中午1:55 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [xuxueli/xxl-job] 如何设置单机并行 (#2529) 感觉这个需求有点奇怪，3秒执行一次，执行却要1分钟，不会冲突？导致数据不一致嘛？ 楼上说的线程池，用不了多久就用光了，没法玩。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 执行过程是占用线程的，在任务执行完之前线程是被一直占用的，后续的定时任务如何持续分配线程？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 嗯，一下没反应过来哈 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
原始感觉就是这个任务调度周期就不太合理。

**Comment by pengten** [comment]
异步执行

**Comment by wind-hx** [comment]
> 可以使用线程池

试过线程池是可以满足的 执行器入口直接将任务丢进线程池可以 但是线程池里使用XxlJobHelper.log会乱串。。。。

**Comment by wind-hx** [comment]
因为业务 500多任务调度 所以每个小时整点这个时间点 大量任务调度排队
会有很多任务执行不过来
想请教一下 大量任务如何并行调度
前几天为了并行调度 把执行器里的核心代码 转到腾讯云的云函数里 这样确实可以并行 300多任务并行无压力 但是半个小时烧了400块钱

**Comment by xiaoxin19950218** [comment]
可以多节点试试------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年8月10日(星期二) 下午5:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xuxueli/xxl-job] 如何设置单机并行 (#2529)

**Comment by wind-hx** [comment]
> 可以多节点试试------------------&nbsp;原始邮件&nbsp;------------------ ***@***.***&gt; 发送时间:&nbsp;2021年8月10日(星期二) 下午5:44 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [xuxueli/xxl-job] 如何设置单机并行 (#2529)

尝试了多节点，有效果但是任务太多还是调度不过来

**Comment by jmq2007** [comment]
@wind-hx 你好，请问后面是怎么实现单机并发的？我看了下源码，目前执行器这里是没有并发的

**Comment by wind-hx** [comment]
> @wind-hx 你好，请问后面是怎么实现单机并发的？我看了下源码，目前执行器这里是没有并发的

用线程池处理了，下面是详细的介绍
<img width="1143" alt="image" src="https://user-images.githubusercontent.com/17685971/160330989-7bb22b80-b69d-4452-b9ae-6d21fe61ae9a.png">
